// Code generated by "stringer -type=ItemType"; DO NOT EDIT.

package line

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[ItemEOF-1]
	_ = x[ItemText-2]
	_ = x[ItemInt-3]
	_ = x[ItemFloat-4]
	_ = x[ItemEOL-5]
	_ = x[ItemSpace-6]
}

const _ItemType_name = "UnknownItemEOFItemTextItemIntItemFloatItemEOLItemSpace"

var _ItemType_index = [...]uint8{0, 7, 14, 22, 29, 38, 45, 54}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
